import { pgTable, text, integer, boolean, timestamp, jsonb, real } from 'drizzle-orm/pg-core';

export const settings = pgTable('settings', {
  id: text('id').primaryKey(),
  openrouterApiKey: text('openrouter_api_key'),
  lobehubUrl: text('lobehub_url'),
  lobehubApiKey: text('lobehub_api_key'),
  lobehubModel: text('lobehub_model'),
  evolutionUrl: text('evolution_url'),
  evolutionApiKey: text('evolution_api_key'),
  stripePubKey: text('stripe_pub_key'),
  stripeSecretKey: text('stripe_secret_key'),
  stripeWebhookSecret: text('stripe_webhook_secret'),
  customAiEnabled: boolean('custom_ai_enabled'),
  customAiUrl: text('custom_ai_url'),
  customAiKey: text('custom_ai_key'),
  customAiModel: text('custom_ai_model'),
  coinsBalance: integer('coins_balance'),
  customJobRoles: jsonb('custom_job_roles'),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const companies = pgTable('companies', {
  id: text('id').primaryKey(),
  corporateName: text('corporate_name').notNull(),
  cnpj: text('cnpj').notNull(),
  city: text('city'),
  state: text('state'),
  plan: text('plan'),
  coinsFranchise: integer('coins_franchise'),
  monthlyRevenueBrl: real('monthly_revenue_brl'),
  status: text('status'),
  tradeName: text('trade_name'),
  activeClientsCount: integer('active_clients_count'),
  companyContext: text('company_context'),
  aiNotes: text('ai_notes'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const employees = pgTable('employees', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  name: text('name').notNull(),
  email: text('email').notNull(),
  department: text('department'),
  role: text('role'),
  allowedModules: jsonb('allowed_modules'),
  status: text('status'),
  passwordHash: text('password_hash'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const purchaseOrders = pgTable('purchase_orders', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  reqNumber: text('req_number'),
  requesterName: text('requester_name'),
  department: text('department'),
  type: text('type'),
  description: text('description'),
  valueBrl: real('value_brl'),
  coinsAmount: integer('coins_amount'),
  status: text('status'),
  approvedBy: text('approved_by'),
  managerObservation: text('manager_observation'),
  requesterRole: text('requester_role'),
  approvedAt: timestamp('approved_at'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const aiUsageLogs = pgTable('ai_usage_logs', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  userId: text('user_id'),
  model: text('model'),
  coinsSpent: integer('coins_spent'),
  promptTokens: integer('prompt_tokens'),
  completionTokens: integer('completion_tokens'),
  totalTokens: integer('total_tokens'),
  funcionalidade: text('funcionalidade'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const customAgents = pgTable('custom_agents', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  label: text('label').notNull(),
  description: text('description'),
  specialty: text('specialty'),
  category: text('category'),
  avatar: text('avatar'),
  color: text('color'),
  icon: text('icon'),
  modelLlm: text('model_llm'),
  provider: text('provider'),
  temperature: real('temperature'),
  context: text('context'),
  objective: text('objective'),
  systemPrompt: text('system_prompt'),
  initialPrompt: text('initial_prompt'),
  instructions: text('instructions'),
  allowedTools: jsonb('allowed_tools'),
  mcpsEnabled: jsonb('mcps_enabled'),
  permissions: jsonb('permissions'),
  status: text('status'),
  createdBy: text('created_by'),
  updatedBy: text('updated_by'),
  isCustom: boolean('is_custom'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const contaazulConfig = pgTable('contaazul_config', {
  id: text('id').primaryKey(),
  companyId: text('company_id').references(() => companies.id),
  clientId: text('client_id'),
  clientSecret: text('client_secret'),
  redirectUri: text('redirect_uri'),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  isConnected: boolean('is_connected'),
  updatedAt: timestamp('updated_at').defaultNow(),
});
