/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedChatfitRouteImport } from './routes/_authenticated/chatfit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChallengesIndexRouteImport } from './routes/_authenticated/challenges.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicReactivateCheckoutRouteImport } from './routes/api/public/reactivate-checkout'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedChallengesNewRouteImport } from './routes/_authenticated/challenges.new'
import { Route as AuthenticatedCIdRouteImport } from './routes/_authenticated/c.$id'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAdminWarningsRouteImport } from './routes/_authenticated/admin.warnings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedCIdIndexRouteImport } from './routes/_authenticated/c.$id.index'
import { Route as ApiPublicHooksStripeWebhookRouteImport } from './routes/api/public/hooks/stripe-webhook'
import { Route as ApiPublicHooksStreakReminderRouteImport } from './routes/api/public/hooks/streak-reminder'
import { Route as ApiPublicHooksSeedColdStartBannersRouteImport } from './routes/api/public/hooks/seed-cold-start-banners'
import { Route as ApiPublicHooksMetricsMonthlyReminderRouteImport } from './routes/api/public/hooks/metrics-monthly-reminder'
import { Route as ApiPublicHooksFitbotPostRouteImport } from './routes/api/public/hooks/fitbot-post'
import { Route as ApiPublicHooksAiDailyPostRouteImport } from './routes/api/public/hooks/ai-daily-post'
import { Route as ApiPublicHooksAbsenceCheckRouteImport } from './routes/api/public/hooks/absence-check'
import { Route as AuthenticatedCIdVsRouteImport } from './routes/_authenticated/c.$id.vs'
import { Route as AuthenticatedCIdSettingsRouteImport } from './routes/_authenticated/c.$id.settings'
import { Route as AuthenticatedCIdRankingRouteImport } from './routes/_authenticated/c.$id.ranking'
import { Route as AuthenticatedCIdProgressRouteImport } from './routes/_authenticated/c.$id.progress'
import { Route as AuthenticatedCIdPodiumRouteImport } from './routes/_authenticated/c.$id.podium'
import { Route as AuthenticatedCIdHistoryRouteImport } from './routes/_authenticated/c.$id.history'
import { Route as AuthenticatedCIdDuelsRouteImport } from './routes/_authenticated/c.$id.duels'
import { Route as AuthenticatedCIdChatRouteImport } from './routes/_authenticated/c.$id.chat'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatfitRoute = AuthenticatedChatfitRouteImport.update({
  id: '/chatfit',
  path: '/chatfit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesIndexRoute =
  AuthenticatedChallengesIndexRouteImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicReactivateCheckoutRoute =
  ApiPublicReactivateCheckoutRouteImport.update({
    id: '/api/public/reactivate-checkout',
    path: '/api/public/reactivate-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesNewRoute =
  AuthenticatedChallengesNewRouteImport.update({
    id: '/challenges/new',
    path: '/challenges/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCIdRoute = AuthenticatedCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWarningsRoute =
  AuthenticatedAdminWarningsRouteImport.update({
    id: '/warnings',
    path: '/warnings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCIdIndexRoute = AuthenticatedCIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const ApiPublicHooksStripeWebhookRoute =
  ApiPublicHooksStripeWebhookRouteImport.update({
    id: '/api/public/hooks/stripe-webhook',
    path: '/api/public/hooks/stripe-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStreakReminderRoute =
  ApiPublicHooksStreakReminderRouteImport.update({
    id: '/api/public/hooks/streak-reminder',
    path: '/api/public/hooks/streak-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSeedColdStartBannersRoute =
  ApiPublicHooksSeedColdStartBannersRouteImport.update({
    id: '/api/public/hooks/seed-cold-start-banners',
    path: '/api/public/hooks/seed-cold-start-banners',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetricsMonthlyReminderRoute =
  ApiPublicHooksMetricsMonthlyReminderRouteImport.update({
    id: '/api/public/hooks/metrics-monthly-reminder',
    path: '/api/public/hooks/metrics-monthly-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFitbotPostRoute =
  ApiPublicHooksFitbotPostRouteImport.update({
    id: '/api/public/hooks/fitbot-post',
    path: '/api/public/hooks/fitbot-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAiDailyPostRoute =
  ApiPublicHooksAiDailyPostRouteImport.update({
    id: '/api/public/hooks/ai-daily-post',
    path: '/api/public/hooks/ai-daily-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbsenceCheckRoute =
  ApiPublicHooksAbsenceCheckRouteImport.update({
    id: '/api/public/hooks/absence-check',
    path: '/api/public/hooks/absence-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCIdVsRoute = AuthenticatedCIdVsRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const AuthenticatedCIdSettingsRoute =
  AuthenticatedCIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCIdRoute,
  } as any)
const AuthenticatedCIdRankingRoute = AuthenticatedCIdRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const AuthenticatedCIdProgressRoute =
  AuthenticatedCIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedCIdRoute,
  } as any)
const AuthenticatedCIdPodiumRoute = AuthenticatedCIdPodiumRouteImport.update({
  id: '/podium',
  path: '/podium',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const AuthenticatedCIdHistoryRoute = AuthenticatedCIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const AuthenticatedCIdDuelsRoute = AuthenticatedCIdDuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)
const AuthenticatedCIdChatRoute = AuthenticatedCIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedCIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/explore': typeof ExploreRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/chatfit': typeof AuthenticatedChatfitRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/warnings': typeof AuthenticatedAdminWarningsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/c/$id': typeof AuthenticatedCIdRouteWithChildren
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/reactivate-checkout': typeof ApiPublicReactivateCheckoutRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/c/$id/chat': typeof AuthenticatedCIdChatRoute
  '/c/$id/duels': typeof AuthenticatedCIdDuelsRoute
  '/c/$id/history': typeof AuthenticatedCIdHistoryRoute
  '/c/$id/podium': typeof AuthenticatedCIdPodiumRoute
  '/c/$id/progress': typeof AuthenticatedCIdProgressRoute
  '/c/$id/ranking': typeof AuthenticatedCIdRankingRoute
  '/c/$id/settings': typeof AuthenticatedCIdSettingsRoute
  '/c/$id/vs': typeof AuthenticatedCIdVsRoute
  '/api/public/hooks/absence-check': typeof ApiPublicHooksAbsenceCheckRoute
  '/api/public/hooks/ai-daily-post': typeof ApiPublicHooksAiDailyPostRoute
  '/api/public/hooks/fitbot-post': typeof ApiPublicHooksFitbotPostRoute
  '/api/public/hooks/metrics-monthly-reminder': typeof ApiPublicHooksMetricsMonthlyReminderRoute
  '/api/public/hooks/seed-cold-start-banners': typeof ApiPublicHooksSeedColdStartBannersRoute
  '/api/public/hooks/streak-reminder': typeof ApiPublicHooksStreakReminderRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/c/$id/': typeof AuthenticatedCIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/explore': typeof ExploreRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/chatfit': typeof AuthenticatedChatfitRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/warnings': typeof AuthenticatedAdminWarningsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/reactivate-checkout': typeof ApiPublicReactivateCheckoutRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/challenges': typeof AuthenticatedChallengesIndexRoute
  '/c/$id/chat': typeof AuthenticatedCIdChatRoute
  '/c/$id/duels': typeof AuthenticatedCIdDuelsRoute
  '/c/$id/history': typeof AuthenticatedCIdHistoryRoute
  '/c/$id/podium': typeof AuthenticatedCIdPodiumRoute
  '/c/$id/progress': typeof AuthenticatedCIdProgressRoute
  '/c/$id/ranking': typeof AuthenticatedCIdRankingRoute
  '/c/$id/settings': typeof AuthenticatedCIdSettingsRoute
  '/c/$id/vs': typeof AuthenticatedCIdVsRoute
  '/api/public/hooks/absence-check': typeof ApiPublicHooksAbsenceCheckRoute
  '/api/public/hooks/ai-daily-post': typeof ApiPublicHooksAiDailyPostRoute
  '/api/public/hooks/fitbot-post': typeof ApiPublicHooksFitbotPostRoute
  '/api/public/hooks/metrics-monthly-reminder': typeof ApiPublicHooksMetricsMonthlyReminderRoute
  '/api/public/hooks/seed-cold-start-banners': typeof ApiPublicHooksSeedColdStartBannersRoute
  '/api/public/hooks/streak-reminder': typeof ApiPublicHooksStreakReminderRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/c/$id': typeof AuthenticatedCIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/entrar': typeof EntrarRoute
  '/explore': typeof ExploreRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/chatfit': typeof AuthenticatedChatfitRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$code': typeof JoinCodeRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/warnings': typeof AuthenticatedAdminWarningsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/c/$id': typeof AuthenticatedCIdRouteWithChildren
  '/_authenticated/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/reactivate-checkout': typeof ApiPublicReactivateCheckoutRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/_authenticated/c/$id/chat': typeof AuthenticatedCIdChatRoute
  '/_authenticated/c/$id/duels': typeof AuthenticatedCIdDuelsRoute
  '/_authenticated/c/$id/history': typeof AuthenticatedCIdHistoryRoute
  '/_authenticated/c/$id/podium': typeof AuthenticatedCIdPodiumRoute
  '/_authenticated/c/$id/progress': typeof AuthenticatedCIdProgressRoute
  '/_authenticated/c/$id/ranking': typeof AuthenticatedCIdRankingRoute
  '/_authenticated/c/$id/settings': typeof AuthenticatedCIdSettingsRoute
  '/_authenticated/c/$id/vs': typeof AuthenticatedCIdVsRoute
  '/api/public/hooks/absence-check': typeof ApiPublicHooksAbsenceCheckRoute
  '/api/public/hooks/ai-daily-post': typeof ApiPublicHooksAiDailyPostRoute
  '/api/public/hooks/fitbot-post': typeof ApiPublicHooksFitbotPostRoute
  '/api/public/hooks/metrics-monthly-reminder': typeof ApiPublicHooksMetricsMonthlyReminderRoute
  '/api/public/hooks/seed-cold-start-banners': typeof ApiPublicHooksSeedColdStartBannersRoute
  '/api/public/hooks/streak-reminder': typeof ApiPublicHooksStreakReminderRoute
  '/api/public/hooks/stripe-webhook': typeof ApiPublicHooksStripeWebhookRoute
  '/_authenticated/c/$id/': typeof AuthenticatedCIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/entrar'
    | '/explore'
    | '/hall-of-fame'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/chatfit'
    | '/checkin'
    | '/feed'
    | '/notifications'
    | '/ranking'
    | '/settings'
    | '/store'
    | '/invite/$code'
    | '/join/$code'
    | '/admin/ai'
    | '/admin/finance'
    | '/admin/invites'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/warnings'
    | '/admin/withdrawals'
    | '/c/$id'
    | '/challenges/new'
    | '/profile/$userId'
    | '/u/$username'
    | '/api/public/checkout'
    | '/api/public/reactivate-checkout'
    | '/admin/'
    | '/challenges/'
    | '/c/$id/chat'
    | '/c/$id/duels'
    | '/c/$id/history'
    | '/c/$id/podium'
    | '/c/$id/progress'
    | '/c/$id/ranking'
    | '/c/$id/settings'
    | '/c/$id/vs'
    | '/api/public/hooks/absence-check'
    | '/api/public/hooks/ai-daily-post'
    | '/api/public/hooks/fitbot-post'
    | '/api/public/hooks/metrics-monthly-reminder'
    | '/api/public/hooks/seed-cold-start-banners'
    | '/api/public/hooks/streak-reminder'
    | '/api/public/hooks/stripe-webhook'
    | '/c/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/entrar'
    | '/explore'
    | '/hall-of-fame'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/chatfit'
    | '/checkin'
    | '/feed'
    | '/notifications'
    | '/ranking'
    | '/settings'
    | '/store'
    | '/invite/$code'
    | '/join/$code'
    | '/admin/ai'
    | '/admin/finance'
    | '/admin/invites'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/warnings'
    | '/admin/withdrawals'
    | '/challenges/new'
    | '/profile/$userId'
    | '/u/$username'
    | '/api/public/checkout'
    | '/api/public/reactivate-checkout'
    | '/admin'
    | '/challenges'
    | '/c/$id/chat'
    | '/c/$id/duels'
    | '/c/$id/history'
    | '/c/$id/podium'
    | '/c/$id/progress'
    | '/c/$id/ranking'
    | '/c/$id/settings'
    | '/c/$id/vs'
    | '/api/public/hooks/absence-check'
    | '/api/public/hooks/ai-daily-post'
    | '/api/public/hooks/fitbot-post'
    | '/api/public/hooks/metrics-monthly-reminder'
    | '/api/public/hooks/seed-cold-start-banners'
    | '/api/public/hooks/streak-reminder'
    | '/api/public/hooks/stripe-webhook'
    | '/c/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/entrar'
    | '/explore'
    | '/hall-of-fame'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/chatfit'
    | '/_authenticated/checkin'
    | '/_authenticated/feed'
    | '/_authenticated/notifications'
    | '/_authenticated/ranking'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/invite/$code'
    | '/join/$code'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/warnings'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/c/$id'
    | '/_authenticated/challenges/new'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/u/$username'
    | '/api/public/checkout'
    | '/api/public/reactivate-checkout'
    | '/_authenticated/admin/'
    | '/_authenticated/challenges/'
    | '/_authenticated/c/$id/chat'
    | '/_authenticated/c/$id/duels'
    | '/_authenticated/c/$id/history'
    | '/_authenticated/c/$id/podium'
    | '/_authenticated/c/$id/progress'
    | '/_authenticated/c/$id/ranking'
    | '/_authenticated/c/$id/settings'
    | '/_authenticated/c/$id/vs'
    | '/api/public/hooks/absence-check'
    | '/api/public/hooks/ai-daily-post'
    | '/api/public/hooks/fitbot-post'
    | '/api/public/hooks/metrics-monthly-reminder'
    | '/api/public/hooks/seed-cold-start-banners'
    | '/api/public/hooks/streak-reminder'
    | '/api/public/hooks/stripe-webhook'
    | '/_authenticated/c/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EntrarRoute: typeof EntrarRoute
  ExploreRoute: typeof ExploreRoute
  HallOfFameRoute: typeof HallOfFameRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  InviteCodeRoute: typeof InviteCodeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicReactivateCheckoutRoute: typeof ApiPublicReactivateCheckoutRoute
  ApiPublicHooksAbsenceCheckRoute: typeof ApiPublicHooksAbsenceCheckRoute
  ApiPublicHooksAiDailyPostRoute: typeof ApiPublicHooksAiDailyPostRoute
  ApiPublicHooksFitbotPostRoute: typeof ApiPublicHooksFitbotPostRoute
  ApiPublicHooksMetricsMonthlyReminderRoute: typeof ApiPublicHooksMetricsMonthlyReminderRoute
  ApiPublicHooksSeedColdStartBannersRoute: typeof ApiPublicHooksSeedColdStartBannersRoute
  ApiPublicHooksStreakReminderRoute: typeof ApiPublicHooksStreakReminderRoute
  ApiPublicHooksStripeWebhookRoute: typeof ApiPublicHooksStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatfit': {
      id: '/_authenticated/chatfit'
      path: '/chatfit'
      fullPath: '/chatfit'
      preLoaderRoute: typeof AuthenticatedChatfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/': {
      id: '/_authenticated/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof AuthenticatedChallengesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/reactivate-checkout': {
      id: '/api/public/reactivate-checkout'
      path: '/api/public/reactivate-checkout'
      fullPath: '/api/public/reactivate-checkout'
      preLoaderRoute: typeof ApiPublicReactivateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/new': {
      id: '/_authenticated/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof AuthenticatedChallengesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$id': {
      id: '/_authenticated/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AuthenticatedCIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/warnings': {
      id: '/_authenticated/admin/warnings'
      path: '/warnings'
      fullPath: '/admin/warnings'
      preLoaderRoute: typeof AuthenticatedAdminWarningsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/c/$id/': {
      id: '/_authenticated/c/$id/'
      path: '/'
      fullPath: '/c/$id/'
      preLoaderRoute: typeof AuthenticatedCIdIndexRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/api/public/hooks/stripe-webhook': {
      id: '/api/public/hooks/stripe-webhook'
      path: '/api/public/hooks/stripe-webhook'
      fullPath: '/api/public/hooks/stripe-webhook'
      preLoaderRoute: typeof ApiPublicHooksStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/streak-reminder': {
      id: '/api/public/hooks/streak-reminder'
      path: '/api/public/hooks/streak-reminder'
      fullPath: '/api/public/hooks/streak-reminder'
      preLoaderRoute: typeof ApiPublicHooksStreakReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/seed-cold-start-banners': {
      id: '/api/public/hooks/seed-cold-start-banners'
      path: '/api/public/hooks/seed-cold-start-banners'
      fullPath: '/api/public/hooks/seed-cold-start-banners'
      preLoaderRoute: typeof ApiPublicHooksSeedColdStartBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/metrics-monthly-reminder': {
      id: '/api/public/hooks/metrics-monthly-reminder'
      path: '/api/public/hooks/metrics-monthly-reminder'
      fullPath: '/api/public/hooks/metrics-monthly-reminder'
      preLoaderRoute: typeof ApiPublicHooksMetricsMonthlyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fitbot-post': {
      id: '/api/public/hooks/fitbot-post'
      path: '/api/public/hooks/fitbot-post'
      fullPath: '/api/public/hooks/fitbot-post'
      preLoaderRoute: typeof ApiPublicHooksFitbotPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-daily-post': {
      id: '/api/public/hooks/ai-daily-post'
      path: '/api/public/hooks/ai-daily-post'
      fullPath: '/api/public/hooks/ai-daily-post'
      preLoaderRoute: typeof ApiPublicHooksAiDailyPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/absence-check': {
      id: '/api/public/hooks/absence-check'
      path: '/api/public/hooks/absence-check'
      fullPath: '/api/public/hooks/absence-check'
      preLoaderRoute: typeof ApiPublicHooksAbsenceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$id/vs': {
      id: '/_authenticated/c/$id/vs'
      path: '/vs'
      fullPath: '/c/$id/vs'
      preLoaderRoute: typeof AuthenticatedCIdVsRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/settings': {
      id: '/_authenticated/c/$id/settings'
      path: '/settings'
      fullPath: '/c/$id/settings'
      preLoaderRoute: typeof AuthenticatedCIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/ranking': {
      id: '/_authenticated/c/$id/ranking'
      path: '/ranking'
      fullPath: '/c/$id/ranking'
      preLoaderRoute: typeof AuthenticatedCIdRankingRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/progress': {
      id: '/_authenticated/c/$id/progress'
      path: '/progress'
      fullPath: '/c/$id/progress'
      preLoaderRoute: typeof AuthenticatedCIdProgressRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/podium': {
      id: '/_authenticated/c/$id/podium'
      path: '/podium'
      fullPath: '/c/$id/podium'
      preLoaderRoute: typeof AuthenticatedCIdPodiumRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/history': {
      id: '/_authenticated/c/$id/history'
      path: '/history'
      fullPath: '/c/$id/history'
      preLoaderRoute: typeof AuthenticatedCIdHistoryRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/duels': {
      id: '/_authenticated/c/$id/duels'
      path: '/duels'
      fullPath: '/c/$id/duels'
      preLoaderRoute: typeof AuthenticatedCIdDuelsRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
    '/_authenticated/c/$id/chat': {
      id: '/_authenticated/c/$id/chat'
      path: '/chat'
      fullPath: '/c/$id/chat'
      preLoaderRoute: typeof AuthenticatedCIdChatRouteImport
      parentRoute: typeof AuthenticatedCIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWarningsRoute: typeof AuthenticatedAdminWarningsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWarningsRoute: AuthenticatedAdminWarningsRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCIdRouteChildren {
  AuthenticatedCIdChatRoute: typeof AuthenticatedCIdChatRoute
  AuthenticatedCIdDuelsRoute: typeof AuthenticatedCIdDuelsRoute
  AuthenticatedCIdHistoryRoute: typeof AuthenticatedCIdHistoryRoute
  AuthenticatedCIdPodiumRoute: typeof AuthenticatedCIdPodiumRoute
  AuthenticatedCIdProgressRoute: typeof AuthenticatedCIdProgressRoute
  AuthenticatedCIdRankingRoute: typeof AuthenticatedCIdRankingRoute
  AuthenticatedCIdSettingsRoute: typeof AuthenticatedCIdSettingsRoute
  AuthenticatedCIdVsRoute: typeof AuthenticatedCIdVsRoute
  AuthenticatedCIdIndexRoute: typeof AuthenticatedCIdIndexRoute
}

const AuthenticatedCIdRouteChildren: AuthenticatedCIdRouteChildren = {
  AuthenticatedCIdChatRoute: AuthenticatedCIdChatRoute,
  AuthenticatedCIdDuelsRoute: AuthenticatedCIdDuelsRoute,
  AuthenticatedCIdHistoryRoute: AuthenticatedCIdHistoryRoute,
  AuthenticatedCIdPodiumRoute: AuthenticatedCIdPodiumRoute,
  AuthenticatedCIdProgressRoute: AuthenticatedCIdProgressRoute,
  AuthenticatedCIdRankingRoute: AuthenticatedCIdRankingRoute,
  AuthenticatedCIdSettingsRoute: AuthenticatedCIdSettingsRoute,
  AuthenticatedCIdVsRoute: AuthenticatedCIdVsRoute,
  AuthenticatedCIdIndexRoute: AuthenticatedCIdIndexRoute,
}

const AuthenticatedCIdRouteWithChildren =
  AuthenticatedCIdRoute._addFileChildren(AuthenticatedCIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChatfitRoute: typeof AuthenticatedChatfitRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedCIdRoute: typeof AuthenticatedCIdRouteWithChildren
  AuthenticatedChallengesNewRoute: typeof AuthenticatedChallengesNewRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedChallengesIndexRoute: typeof AuthenticatedChallengesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChatfitRoute: AuthenticatedChatfitRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedCIdRoute: AuthenticatedCIdRouteWithChildren,
  AuthenticatedChallengesNewRoute: AuthenticatedChallengesNewRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedChallengesIndexRoute: AuthenticatedChallengesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EntrarRoute: EntrarRoute,
  ExploreRoute: ExploreRoute,
  HallOfFameRoute: HallOfFameRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  InviteCodeRoute: InviteCodeRoute,
  JoinCodeRoute: JoinCodeRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicReactivateCheckoutRoute: ApiPublicReactivateCheckoutRoute,
  ApiPublicHooksAbsenceCheckRoute: ApiPublicHooksAbsenceCheckRoute,
  ApiPublicHooksAiDailyPostRoute: ApiPublicHooksAiDailyPostRoute,
  ApiPublicHooksFitbotPostRoute: ApiPublicHooksFitbotPostRoute,
  ApiPublicHooksMetricsMonthlyReminderRoute:
    ApiPublicHooksMetricsMonthlyReminderRoute,
  ApiPublicHooksSeedColdStartBannersRoute:
    ApiPublicHooksSeedColdStartBannersRoute,
  ApiPublicHooksStreakReminderRoute: ApiPublicHooksStreakReminderRoute,
  ApiPublicHooksStripeWebhookRoute: ApiPublicHooksStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
