// Build entrypoint.
//
// Cloudflare ("Pages as Workers"): the deploy step `wrangler versions upload`
// reads wrangler.jsonc and expects `.vercel/output/static/_worker.js`. That
// file is generated by the `@cloudflare/next-on-pages` adapter — which must
// run its FULL pipeline (next build + Vercel build + worker packaging). The
// `--skip-build` flag CANNOT be used: it skips the Vercel build that produces
// `.vercel/output/config.json`, which the adapter requires.
//
// The adapter itself only works on Linux/macOS (on Windows its shellac layer
// cannot spawn `npm`/`npx` — known limitation). So:
//   - Windows (local dev): plain `next build` is enough.
//   - Linux/macOS (Cloudflare build): run the full `next-on-pages` pipeline.

const { spawnSync } = require("child_process");

const isWindows = process.platform === "win32";

const run = (cmd, args) => {
  return spawnSync(cmd, args, {
    stdio: "inherit",
    shell: isWindows,
  });
};

const fail = (res, label) => {
  if (res.error) {
    console.error(`[build] Failed to spawn ${label}:`, res.error.message);
  }
  process.exit(res.status ?? 1);
};

if (isWindows) {
  console.log("[build] Windows (local dev) — running `next build` only.");
  const res = run("next", ["build"]);
  if (res.status !== 0 || res.error) fail(res, "next");
} else {
  console.log(
    "[build] Linux/macOS — running full next-on-pages pipeline " +
    "(next build + Vercel build + Worker generation)..."
  );
  const res = run("next-on-pages", []);
  if (res.status !== 0 || res.error) fail(res, "next-on-pages");
}

console.log("[build] Done.");
